#!/usr/bin/env python3

# TODO

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored

from twython import Twython
from twython import TwythonAuthError, TwythonError, TwythonRateLimitError


def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    screen_name = sys.argv[1]
    
    # get screen_name's tweets
    tweets = helpers.get_user_timeline(screen_name)
    if tweets == None:
        print("We couldn't get the tweets from " + screen_name)
        sys.exit()
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    score = 0
    for tweet in tweets:
        # analyze word
        score = analyzer.analyze(tweet)
        
        if score > 0.0:
            print(colored(" 1 " + tweet, "green"))
        elif score < 0.0:
            print(colored("-1 " + tweet, "red"))
        else:
            print(colored(" 0 " + tweet, "yellow"))


if __name__ == "__main__":
    main()
